### ISSUE TITLE
Quick Start

### ISSUE THREAD

**Issue by Zorig** [reactjs/mn.react.dev#340]

**Comment by Zorig** [comment]
@gracexnn

**Comment by gracexnn** [comment]
Pull request-ээс түүж аваад Merge хийж болдог юм болов уу? эсвэл тус тусад нь хүсэлт явуулах ёстой юу?

**Comment by Zorig** [comment]
> Pull request-ээс түүж аваад Merge хийж болдог юм болов уу? эсвэл тус тусад нь хүсэлт явуулах ёстой юу?

Шаардлага нь юу билээ хамгийн сүүлд орсон өөрчлөлтийг аваад л орчуулаад явуулахад болно шүү дээ
